#!/bin/bash

# Caminho para o arquivo de comandos
COMMANDS_FILE="tests/tests_errs_parser.txt"

# Função para executar um comando no minishell e verificar a saída
run_test() {
    local command="$1"
    local expected_output="$2"
    local output

    # Usa echo para evitar problemas com bytes nulos
    output=$(echo "$command" | ./minishell)
    if [[ $output == *"$expected_output"* ]]; then
        echo "Test passed: $command"
    else
        echo "Test failed: $command"
        echo "Expected: $expected_output"
        echo "Got: $output"
    fi
}

# Lê o arquivo de comandos linha por linha e executa cada comando no minishell
while IFS= read -r line; do
    case "$line" in
        "cat arquivo.txt || wc -l")
            run_test "$line" "syntax error near unexpected token '|'"
            ;;
        "cat arquivo.txt | wc -l |")
            run_test "$line" "multiples lines command not suported"
            ;;
        "| cat arquivo.txt | grep \"palavra\"")
            run_test "$line" "syntax error near unexpected token '|'"
            ;;
        "ls -l >| sort")
            run_test "$line" "syntax error near unexpected token '|'"
            ;;
        "ls -l >>| head -n 10")
            run_test "$line" "syntax error near unexpected token '|'"
            ;;
        "ps aux >>> wc -l")
            run_test "$line" "syntax error near unexpected token '>'"
            ;;
        "ps aux >< grep \"firefox\"")
            run_test "$line" "syntax error near unexpected token '<'"
            ;;
        "ps aux >>>>>> grep \"^username\"")
            run_test "$line" "syntax error near unexpected token '>>'"
            ;;
        "cat \"arquivo.txt | tr ' ' '\n' | sort | uniq -c")
            run_test "$line" "syntax error: unclosed quotes"
            ;;
        "grep -n 'erro\" arquivo.log | less")
            run_test "$line" "syntax error: unclosed quotes"
            ;;
        "find . -name \"*.tmp\" | xargs rm >")
            run_test "$line" "syntax error near unexpected token '>'"
            ;;
        "df -h | sort -k 5 -n >>")
            run_test "$line" "syntax error near unexpected token '>'"
            ;;
        "ls -lt ||| head -n 5")
            run_test "$line" "syntax error near unexpected token '|'"
            ;;
        *)
            echo "No expected output defined for: $line"
            ;;
    esac
done < "$COMMANDS_FILE"